{% set name = "pypy3.6" %}
{% set version = "7.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/pypy/pypy/downloads/{{ name }}-v{{ version }}-src.tar.bz2
    sha256: 0c2cc3229da36c6984baee128c8ff8bb4516d69df1d73275dc4622bf249afa83
    folder: pypy3
    patches:
      - patches/fficurses.patch
      - patches/tklib_build.patch
      - patches/clibffi.patch  # [osx]
      - patches/darwin.patch  # [osx]
      - patches/distutils.patch
      # Patches by @mingwandroid from python-feedstock
      - patches/0009-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0012-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0013-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0020-Use-ranlib-from-env-if-env-variable-is-set.patch

build:
  number: 1
  skip: True  # [win]
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3
    - pkg-config
    - pycparser
  host:
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - expat
    - ncurses
    - gdbm
    - xz
    - tk
    - bzip2
    - xorg-libx11  # [linux]
  run:
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - ncurses
    - gdbm
    - xz
    - expat
    - bzip2
  run_constrained:
    - pypy3.5 ==99999999999

test:
  commands:
    - pypy3 --help

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: PyPy is a Python interpreter and just-in-time compiler.

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
    - isuruf
    - ocefpaf
