{% set name = "pypy3.6" %}
{% set version = "7.1.1b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.1.1-src.tar.bz2
    fn: pypy3.6-v7.1.1-src.tar.bz2
    sha256: 6a3ef876e3691a54f4cff045028ec3be94ab9beb2e99f051b83175302c1899a8
    folder: pypy3
    patches:
      - fficurses.patch
      - minimal_curses.patch
      - tklib_build.patch
      - clibffi.patch  # [osx]
      - darwin.patch  # [osx]

build:
  number: 0
  skip: True  # [win]
  skip_compile_pyc:
    - lib*

requirements:
  build:
    - {{ compiler('c') }}
    - python >=2.7,<3
  host:
    - python >=2.7,<3
    - libunwind >=4.0  # [osx]
    - pkg-config
    - pycparser
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - expat
    - ncurses >=6.0
    - gdbm
    - xz
    - tk
    - bzip2
    - xorg-libx11  # [linux]
  run:
    - libunwind >=4.0  # [osx]
    - openssl
    - libffi
    - sqlite
    - tk
    - zlib
    - bzip2
    - ncurses >=6.0
    - gdbm
    - xz
    - expat
    - bzip2
  run_constrained:
    - pypy3.5 ==99999999999

test:
  commands:
    - pypy3 --help

about:
    home: http://pypy.org/
    license: MIT
    license_family: MIT
    license_file: pypy3/LICENSE
    summary: PyPy is a Python interpreter and just-in-time compiler.

extra:
  recipe-maintainers:
    - omerbenamram
    - ohadravid
